# Autogenerated file
def render(accept_type, input_name, form_action, input_label):
    yield """
<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"utf-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">
    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">
    <title>Classification tool</title>
    <link href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\" rel=\"stylesheet\"/>
    <link href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\"/>
</head>
    <body>
        """
# Autogenerated file
    def render1(*a, **d):
        yield """<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">
    <a class=\"navbar-brand\" href=\"/\">Classification tool</a>
    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">
        <span class=\"navbar-toggler-icon\"></span>
    </button>
    <div class=\"collapse navbar-collapse\" id=\"navbarNav\">
        <ul class=\"navbar-nav\">
            <li class=\"nav-item\">
                <a class=\"nav-link\" href=\"/models\">Model list</a>
            </li>
            <li class=\"nav-item\">
                <a class=\"nav-link\" href=\"/images\">Image list</a>
            </li>
        </ul>
    </div>
</nav>"""
    yield from render1()
    yield """
        <main class=\"container\">
            <div class=\"p-3\">
                <h1>Upload """
    yield str(input_label)
    yield """</h1>
                <div class=\"alert alert-secondary\">Please be patinent. Uploading file can take up to several minutes</div>
                <form action='"""
    yield str(form_action)
    yield """' enctype=\"multipart/form-data\" method='POST'>
                    <div class=\"form-group row\">
                        <label class=\"btn btn-primary col-sm-12\">
                            <i class=\"fa fa-image\"></i>"""
    yield str(input_label)
    yield """<input id='file' type='file' accept='"""
    yield str(accept_type)
    yield """' name='"""
    yield str(input_name)
    yield """' style=\"display: none;\"/>
                        </label>
                        <input class=\"btn btn-primary mt-3 col-sm-4\" type='submit' value='submit' />
                    </div>
                </form>
            </div>
        </main>
    </body>
</html>"""
