# Autogenerated file
def render(file_list):
    yield """
<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"utf-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">
    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">
    <title>Classification tool</title>
    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">
</head>
    <body>
        """
# Autogenerated file
    def render1(*a, **d):
        yield """<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">
    <a class=\"navbar-brand\" href=\"/\">Classification tool</a>
    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">
        <span class=\"navbar-toggler-icon\"></span>
    </button>
    <div class=\"collapse navbar-collapse\" id=\"navbarNav\">
        <ul class=\"navbar-nav\">
            <li class=\"nav-item\">
                <a class=\"nav-link\" href=\"/models\">Model list</a>
            </li>
            <li class=\"nav-item\">
                <a class=\"nav-link\" href=\"/images\">Image list</a>
            </li>
        </ul>
    </div>
</nav>
"""
    yield from render1()
    yield """
        <main class=\"container py-5\">
            <div class=\"row\">
                """
    for file in file_list:
        yield """
                <div class=\"col-sm-4\">
                    <div class=\"card mb-4 shadow-sm\">
                        <div name=\"spinner_"""
        yield str(file)
        yield """\" class=\"spinner-border\" role=\"status\">
                            <span class=\"sr-only\">Loading...</span>
                        </div>
                        <img name=\""""
        yield str(file)
        yield """\" onload=\"imageLoad(this.name)\" class=\"card-img-top\" src=\""""
        yield str(file)
        yield """\" alt=\""""
        yield str(file.rsplit('/')[-1])
        yield """\">
                        <div class=\"card-body\">
                            <p class=\"card-text\">"""
        yield str(file.rsplit('/')[-1])
        yield """</p>
                        </div>
                    </div>
                </div>
                """
    yield """
            </div>
        </main>
        <script>
            function imageLoad(name) """
    yield """{
                var div_element = document.getElementsByName(\"spinner_\" + name)[0];
                div_element.style.display = \"none\";
            }
        </script
    </body>
</html>


"""
