# Autogenerated file
def render(file_list, back_href, page, render_next_page, model, class_name):
    yield """
<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"utf-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">
    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">
    <title>Classification tool</title>
    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">
</head>
    <body>
        <script>
            function imageLoad(name) """
    yield """{
                var div_element = document.getElementsByName(\"spinner_\" + name)[0];
                div_element.style.display = \"none\";
            }
        </script>
        """
# Autogenerated file
    def render1(*a, **d):
        yield """<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">
    <a class=\"navbar-brand\" href=\"/\">Classification tool</a>
    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">
        <span class=\"navbar-toggler-icon\"></span>
    </button>
    <div class=\"collapse navbar-collapse\" id=\"navbarNav\">
        <ul class=\"navbar-nav\">
            <li class=\"nav-item\">
                <a class=\"nav-link\" href=\"/models\">Model list</a>
            </li>
            <li class=\"nav-item\">
                <a class=\"nav-link\" href=\"/images\">Image list</a>
            </li>
        </ul>
    </div>
</nav>
"""
    yield from render1()
    yield """
        <main class=\"container py-5\">
            <a href=\""""
    yield str(back_href)
    yield """\"><h2>Go back</h2></a>
            <div class=\"row\">
                """
    for file in file_list:
        yield """
                <div class=\"col-sm-4\">
                    <div class=\"card mb-4 shadow-sm\">
                        <div name=\"spinner_"""
        yield str(file)
        yield """\" class=\"spinner-border\" role=\"status\">
                            <span class=\"sr-only\">Loading...</span>
                        </div>
                        <img name=\""""
        yield str(file)
        yield """\" onload=\"imageLoad(this.name)\" class=\"card-img-top\" src=\""""
        yield str(file)
        yield """\" alt=\""""
        yield str(file.rsplit('/')[-1])
        yield """\">
                        <div class=\"card-body\">
                            <a target=\"_blank\" href=\"/image?model="""
        yield str(model)
        yield """&class="""
        yield str(class_name)
        yield """&file="""
        yield str(file.rsplit('/')[-1])
        yield """\"><p class=\"card-text\">"""
        yield str(file.rsplit('/')[-1])
        yield """</p></a>
                        </div>
                    </div>
                </div>
                """
    yield """
            </div>
            """
    if page != 1:
        yield """
            <button type=\"button\" class=\"btn btn-outline-primary\" onclick=\"location.href='/images_visible?model="""
        yield str(model)
        yield """&class="""
        yield str(class_name)
        yield """&page="""
        yield str(page-1)
        yield """'\">Previous page</button>
            """
    yield """
            """
    if render_next_page:
        yield """
            <button type=\"button\" class=\"btn btn-outline-primary\" onclick=\"location.href='/images_visible?model="""
        yield str(model)
        yield """&class="""
        yield str(class_name)
        yield """&page="""
        yield str(page+1)
        yield """'\">Next page</button>
            """
    yield """
        </main>
    </body>
</html>


"""
