# Autogenerated file
def render(item_list, param_name, item_href, back_href, counter_list=None, param_dict=None):
    yield """
<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"utf-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">
    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">
    <title>Classification tool</title>
    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">
</head>
    <body>
        """
# Autogenerated file
    def render1(*a, **d):
        yield """<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">
    <a class=\"navbar-brand\" href=\"/\">Classification tool</a>
    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">
        <span class=\"navbar-toggler-icon\"></span>
    </button>
    <div class=\"collapse navbar-collapse\" id=\"navbarNav\">
        <ul class=\"navbar-nav\">
            <li class=\"nav-item\">
                <a class=\"nav-link\" href=\"/models\">Model list</a>
            </li>
            <li class=\"nav-item\">
                <a class=\"nav-link\" href=\"/images\">Image list</a>
            </li>
        </ul>
    </div>
</nav>
"""
    yield from render1()
    yield """
        <main class=\"container\">
            <div class=\"p-3\">
                <h1>
                Browse images
                """
    if param_dict != None:
        yield """
                """
        for key, value in param_dict.items():
            yield """ 
                /"""
            yield str(value)
            yield """
                """
        yield """
                """
    yield """
                </h1>
                <a href=\""""
    yield str(back_href)
    yield """\"><h2>Go back</h2></a>
                """
    if param_dict != None and 'model' in param_dict.keys() and 'class' in param_dict.keys():
        yield """
                <a href=\"/images_visible?model="""
        yield str(param_dict['model'])
        yield """&class="""
        yield str(param_dict['class'])
        yield """\">View image cards<h2></h2></a>
                """
    yield """
            </div>
            """
# Autogenerated file
    def render2(item_list, delete_endpoint, param_name, item_href=None, counter_list=None, param_dict=None):
        yield """
<div class=\"container-fluid\">
    <table class=\"table\">
        <thead>
            <tr>
                <th scope=\"col\">"""
        yield str(param_name)
        yield """</th>
                <th scope=\"col\">action</th>
                """
        if counter_list != None:
            yield """
                <th scope=\"col\">occurances</th>
                """
        yield """
            </tr>
        </thead>
        <tbody>
            """
        for i in range(len(item_list)):
            yield """
                <tr>
                    <td>
                        """
            if item_href != None:
                yield """
                        <button type=\"button\" class=\"btn btn-outline-primary\" onclick=\"location.href='"""
                yield str(item_href)
                yield str(item_list[i])
                yield """'\">"""
                yield str(item_list[i])
                yield """</button>
                        """
            else:
                yield """
                        <span>"""
                yield str(item_list[i])
                yield """</p>
                        """
            yield """
                    </td>
                    <td>
                        <button name=\""""
            yield str(item_list[i])
            yield """\" onclick=\"confirmDeleteAction(this.name)\" type=\"button\" class=\"btn btn-outline-primary\">Delete</button>
                    </td>
                    """
            if counter_list != None:
                yield """
                    <td>
                        <span class=\"badge badge-pill badge-primary\">"""
                yield str(counter_list[i])
                yield """</span>
                    </td>
                    """
            yield """
                </tr>
            """
        yield """
        </tbody>
    </table>
</div>

<script>
    function confirmDeleteAction(name) """
        yield """{
        if (window.confirm(\"Are you sure you want to delete:\" + name + \" ?\")) """
        yield """{
            var lastIndex = window.location.href.lastIndexOf(\"/\");
            var param_string = \"\"
            """
        if param_dict != None:
            yield """
            """
            for key, value in param_dict.items():
                yield """
            param_string = param_string + \""""
                yield str(key)
                yield """\" + \"=\" + \""""
                yield str(value)
                yield """\" + \"&\"
            """
            yield """
            """
        yield """
            window.location.href = window.location.href.slice(0, lastIndex+1) + \""""
        yield str(delete_endpoint)
        yield """\" +\"?\" + param_string +  \""""
        yield str(param_name)
        yield """\" + \"=\" + name;
        }
    }
</script>
"""
    yield from render2(item_list, "delete_images", param_name, item_href, counter_list, param_dict)
    yield """
        </main>
    </body>
</html>

"""
